language: csharp
dist: trusty
sudo: required
mono: none
services:
  - mongodb
  - redis-server
  - postgresql
  - docker
dotnet: 1.0.4
addons:
  postgresql:  "9.5"
  apt:
    packages:
      - google-cloud-sdk
before_script:
  - gcloud beta emulators datastore start &
  - $(gcloud beta emulators datastore env-init)
script:
  - chmod +x ./Build.sh && ./Build.sh --quiet verify