language: csharp
dist: trusty
sudo: required
mono: none
services:
  - mongodb
  - redis-server
  - postgresql
  - docker
dotnet: 1.0.4
addons:
  postgresql:  "9.5"
before_install:
  - docker pull singularities/datastore-emulator
  - docker run --rm -d -e DATASTORE_PROJECT_ID=rapidcore-local -e DATASTORE_LISTEN_ADDRESS=0.0.0.0:8081 -p 8081:8081 singularities/datastore-emulator
script:
  - chmod +x ./Build.sh && ./Build.sh --quiet verify