language: csharp
dist: trusty
sudo: required
mono: none
services:
  - mongodb
  - redis-server
  - postgresql
  - docker
dotnet: 2.1.200
addons:
  postgresql: '9.5'
before_install:
  - docker pull singularities/datastore-emulator
  - docker run --rm -d -e DATASTORE_PROJECT_ID=rapidcore-local -e DATASTORE_LISTEN_ADDRESS=0.0.0.0:8081 -p 8081:8081 singularities/datastore-emulator
  - docker run --rm -d -e ACCEPT_EULA=Y -e SA_PASSWORD="sql-s3rv3r%" -e MSSQL_PID=Developer -p 1433:1433 microsoft/mssql-server-linux:2017-CU6
script:
  - chmod +x ./Build.sh && ./Build.sh --quiet verify
deploy:
  - provider: gcs
    access_key_id: GOOG3WOQ425K2J262RM3
    secret_access_key:
      secure: AKGMdkOY4dPwPAZQGPmHULiMidMcdacQYKHPyqANsqnooKEpcdL3AwXRsv9YIbz4x/bkDdHsh95oGoePZn9kNbilb8HC9NgwfA7/+7o/yROSMpX3DPu3wD5Ipc7UOULlU4Nhj7QMHdEuizTTnig7Kgwc+Zfgo5V7/KN8kYcglittIdw0aSr1VKWpKBowMd2OpukQCFEtWz+ca3/G3hNic1v4DGCyUmMoFW0S1nrueoteTbgqUx/WBSpwhzNHCWPt0WjoaSNOak8EjDFcLNqtbPZ63eC/Uo2OTLRIIJKdmt26TuGPHq7oj8izeKsDbc1D6vWYpvu8BJ/EQC5c4F1H9gQIfLgoYASHqIxuLlzY2OQ7Gm8K7mwj+pCkn27KSmlPu1HANTPI0KtJVqnCHq2qN1jBWw1WZs9k/0KQfoJkd/xnofDjCs/CF9iiPtePqOjX40C5LFgg/Wuxwz2AIeALM/Lcj187hrKIHNQdYLxnABJT3TwW0T5bevWUol+ZoXxs7RceLGabJCuAUHVNyyr7WCpVxqJLFLOin0hDCx0xtsv3T+KRD2OjAE3y/5qHRPdmp16l6iZh6yYN0GNiacXmU2RQR+YjNp/x61P4g0kSNS44QhQYukbXMlTzl3eM8l3VQxteplKzP4ljlw6Xx1YHWTZRpd3q6/k67UeChH/BgBc=
    bucket: docs.rapidcore.io
    local-dir: docs-generated
    skip_cleanup: true
    acl: public-read
    on:
      repo: rapidcore/rapidcore
      tags: true
  - provider: gcs
    access_key_id: GOOG3WOQ425K2J262RM3
    secret_access_key:
      secure: AKGMdkOY4dPwPAZQGPmHULiMidMcdacQYKHPyqANsqnooKEpcdL3AwXRsv9YIbz4x/bkDdHsh95oGoePZn9kNbilb8HC9NgwfA7/+7o/yROSMpX3DPu3wD5Ipc7UOULlU4Nhj7QMHdEuizTTnig7Kgwc+Zfgo5V7/KN8kYcglittIdw0aSr1VKWpKBowMd2OpukQCFEtWz+ca3/G3hNic1v4DGCyUmMoFW0S1nrueoteTbgqUx/WBSpwhzNHCWPt0WjoaSNOak8EjDFcLNqtbPZ63eC/Uo2OTLRIIJKdmt26TuGPHq7oj8izeKsDbc1D6vWYpvu8BJ/EQC5c4F1H9gQIfLgoYASHqIxuLlzY2OQ7Gm8K7mwj+pCkn27KSmlPu1HANTPI0KtJVqnCHq2qN1jBWw1WZs9k/0KQfoJkd/xnofDjCs/CF9iiPtePqOjX40C5LFgg/Wuxwz2AIeALM/Lcj187hrKIHNQdYLxnABJT3TwW0T5bevWUol+ZoXxs7RceLGabJCuAUHVNyyr7WCpVxqJLFLOin0hDCx0xtsv3T+KRD2OjAE3y/5qHRPdmp16l6iZh6yYN0GNiacXmU2RQR+YjNp/x61P4g0kSNS44QhQYukbXMlTzl3eM8l3VQxteplKzP4ljlw6Xx1YHWTZRpd3q6/k67UeChH/BgBc=
    bucket: preview-docs.rapidcore.io
    local-dir: docs-generated
    skip_cleanup: true
    acl: public-read
    on:
      repo: rapidcore/rapidcore
      tags: false
      branch: master
addons:
  sonarcloud:
    organization: "rapidcore"
    token:
      secure: "SN4dRpE/DPio6b1IZfqdPGOGpZYjPdB2iSE6tF3Uf7/8Dm4tWZwgfHBfCb6ezfKZWzz5nSOASEoKM5ySLJPgCUR53KxCf6E2D10IFMJPYI58L4abdJQP+UBEbmT+LOEnsoR07p+LG4YMRQdf359rXeOOM7z25D+I3orayTtVdhn0JyOIxV3C9uLAWc+2f0sVbHDA6zPYnrhpFmPrQ/J8slrCC6o+n+GhSf5BhZIJMhIuAEg2KWaE88gDV0ebuCjA+ImGafIHSPBaBddE1I9qUMXgLn7nqv5Mdj3tgNminvEEz2duThp+l8Ym0rIfsLANPNH2i+iVG26j1OepjAw/RQNxQgnxqbaghebnPmrBuMsIT1GgZLtEyNyTPl92e8BXZ3IxQLQQXi2iksleR2BDbTpy/QKg33XLSDpbjnYAEuPBgBPZ27h3tHw4xsAMgIw8wrRlAoSkdmWHIOrgP+pKEHiLKUcAYuVKH9IVTOXHCiB0Cee6AMsEs46h0ZgpE5JkWzsy+k6RzrwmD64RxBUsGuDkupEm5BpMOj2AXsTa6nqcEKh6PEwnCHuRvPJawpn6M0RHIBN0GsI/V8FH7hMJ8MJ+957LAk4YGLt1FhC/aQDiwASPImBE/cDhi5uFFcFBblYxN0PEIM+YePhohTN/Pc8d/A+hn6pLPrwwhkWfSCw="

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - sonar-scanner
