version: '{build}'
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
nuget:  
  disable_publish_on_pr: true
environment:
  SONARCLOUD_TOKEN:
    secure: Tf/wMjCgA2eNaYLOWhCCUGRD6I5V75LNmfMHx54IOJZq2HX/VDpzTgDb1UUlxmt+
build_script:
- ps: .\Build.ps1
test: off
artifacts:
- path: .\artifacts\*.nupkg
  name: NuGet
deploy:
- provider: NuGet
  name: stable
  api_key:
    secure: Qek6svTX1SpK3gObDBpSD4szPqTfWgOhDJys4ShLmK26l7MtZg8u3+FlWI5MyHKi
  on:
    appveyor_repo_tag: true
- provider: NuGet
  name: preview
  api_key:
    secure: Qek6svTX1SpK3gObDBpSD4szPqTfWgOhDJys4ShLmK26l7MtZg8u3+FlWI5MyHKi
  on:
    branch: master