version: "2"

services:
  mongo:
    image: "mongo:3.4"
    ports:
      - "27017:27017"

  redis:
    image: redis:3.2
    ports:
      - "6379:6379"

  redis-ui:
    image: rediscommander/redis-commander
    environment:
      REDIS_HOSTS: local:redis:6379
    ports:
      - 63791:8081

  postgresdb:
    image: postgres:10.1-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 
    ports:
      - 5432:5432

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: sql-s3rv3r%
      MSSQL_PID: Developer
    ports:
      - "1433:1433"

  mkdocs:
    image: rapidcore:mkdocs
    build:
        context: .
        dockerfile: Dockerfile.mkdocs
    volumes:
      - .:/app/repository
    ports:
      - 8000:8000
