version: "2"

services:
  mongo:
    image: "mongo:3.4"
    ports:
      - "27017:27017"

  redis:
    image: redis:3.2
    ports:
      - "6379:6379"

  postgresdb:
    image: postgres:10.1-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 
    ports:
      - 5432:5432

  sqlserver:
    image: microsoft/mssql-server-linux:2017-CU6
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: sql-s3rv3r%
      MSSQL_PID: Developer
    ports:
      - "1433:1433"
  
  datastore:
    image: singularities/datastore-emulator
    environment:
      - DATASTORE_PROJECT_ID=rapidcore-local
      - DATASTORE_LISTEN_ADDRESS=0.0.0.0:8081
    ports:
      - 8081:8081

  datastore-ui:
    image: rapidcore:datastore-ui
    environment:
      PROJECT_ID: rapidcore-local
      UI_PORT: 8282
      DATASTORE_ENDPOINT: datastore:8081
    build:
        context: .
        dockerfile: Dockerfile.dsui
    ports:
      - 8282:8282
    depends_on:
      - datastore
    links:
      - datastore

  mkdocs:
    image: rapidcore:mkdocs
    build:
        context: .
        dockerfile: Dockerfile.mkdocs
    volumes:
      - .:/app/repository
    ports:
      - 8000:8000
