version: "2"

services:
  mongo:
    image: "mongo:3.4"
    ports:
      - "27017:27017"
  redis:
    image: redis:3.2
    ports:
      - "6379:6379"
  postgresdb:
    image: postgres:10.1-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 
    ports:
      - 5432:5432

  mkdocs:
    image: rapidcore:mkdocs
    build:
        context: .
        dockerfile: Dockerfile.mkdocs
    volumes:
      - .:/app/repository
    ports:
      - 8000:8000
