site_name: RapidCore Docs
theme: readthedocs
repo_url: https://github.com/rapidcore/rapidcore/
nav:
  - RapidCore: index.md
  - Audit:
      - Introduction: Audit/Introduction.md
      - AuditDiffer: Audit/AuditDiffer.md
      - Value masking: Audit/ValueMasking.md
  - Mongo DB:
      - Connection: MongoDB/RapidCore.Mongo.MongoDbConnection.md
      - Indexes: MongoDB/Indexes.md
  - Dependency injection:
      - IRapidContainerAdapter: DependencyInjection/IRapidContainerAdapter.md
  - Diffing:
      - Diff object instances: Diffing/StateChangeFinder.md
  - Environment:
      - Variables: RapidCore.Environment/EnvironmentVariables.md
  - Generally useful attributes:
      - Ignore: Attributes/Ignore.md
  - Globalization:
      - Countries: RapidCore.Globalization/ISO3166_Countries.md
      - Currencies: RapidCore.Globalization/ISO4217_Currencies.md
      - Date and time: RapidCore.Globalization/DateAndTime.md
  - Google Cloud Datastore:
      - Introduction: Datastore/Introduction.md
      - ORM: Datastore/Orm.md
      - Connection: Datastore/Connection.md
      - Connected test base: Datastore/TestBase.md
  - Locking:
      - Distributed app lock: RapidCore.Locking/DistributedAppLock.md
  - SqlServer:
      - Distributed app lock: SqlServer/Locking.md
  - Network:
      - DNS: RapidCore.Network/HostnameToIP.md
      - Predictable http client: RapidCore.Network/HttpClient.md
  - Reflection:
      - Attributes: RapidCore.Reflection/Attributes.md
      - Methods: RapidCore.Reflection/Methods.md
      - Nullable: RapidCore.Reflection/Nullable.md
      - Properties: RapidCore.Reflection/Properties.md
      - Traversing an object instance: RapidCore.Reflection/InstanceTraverser.md
  - Threading:
      - Async/Await: RapidCore.Threading/AsyncAwait.md
