site_name: RapidCore Docs
theme: readthedocs
repo_url: https://github.com/rapidcore/rapidcore/
pages:
  - RapidCore: index.md
  - Mongo DB:
      - Connection: MongoDB/RapidCore.Mongo.MongoDbConnection.md
      - Indexes: MongoDB/Indexes.md
  - Environment:
      - Variables: RapidCore.Environment/EnvironmentVariables.md
  - Globalization:
      - Countries: RapidCore.Globalization/ISO3166_Countries.md
      - Currencies: RapidCore.Globalization/ISO4217_Currencies.md
      - Date and time: RapidCore.Globalization/DateAndTime.md
  - Google Cloud Datastore:
      - Introduction: Datastore/Introduction.md
      - ORM: Datastore/Orm.md
      - Connection: Datastore/Connection.md
      - Connected test base: Datastore/TestBase.md
  - Locking:
      - Distributed app lock: RapidCore.Locking/DistributedAppLock.md
  - Network:
      - DNS: RapidCore.Network/HostnameToIP.md
      - Predictable http client: RapidCore.Network/HttpClient.md
  - Reflection:
      - Attributes: RapidCore.Reflection/Attributes.md
      - Methods: RapidCore.Reflection/Methods.md
      - Properties: RapidCore.Reflection/Properties.md
  - Threading:
      - Async/Await: RapidCore.Threading/AsyncAwait.md
