name: Master workflow

on:
  push:
    branches:
      - 159-start-using-github-actions-for-cicd

env:
  DOTNET_SDK_VERSION: '2.1.607'
  DOCS_BUCKET: i-am-just-testing-stuff-1961s45g4sd6g54sd9hgs4gh54s
  GENERATED_DOCS_ARTIFACT: generated-docs
  NUGET_SOURCE: https://api.nuget.org/v3/index.json

jobs:
  # The build job, builds the entire solution.
  # We start with this job - even though building
  # is also done during analysis - as it should
  # allow us to fail the workflow quickly (none
  # of the other jobs makes sense to run, if we
  # cannot build the code!).
  build-code:
    name: Build code
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_SDK_VERSION }}
      - name: Build the solution in release mode
        run: dotnet build -c Release

  # Build the documentation (and do nothing with it).
  # This is just to prove that the documentation is valid
  # and that we will be able to build and publish it when
  # we merge the PR.
  build-docs:
    name: Build documentation
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Build documentation
        shell: bash
        run: |
          docker build -t rapidcore:mkdocs -f Dockerfile.mkdocs .
          docker run --volume=${PWD}:/app/repository:rw -p 8000:8000 -t rapidcore:mkdocs build
      - uses: actions/upload-artifact@v1
        with:
          name: ${{ env.GENERATED_DOCS_ARTIFACT }}
          path: ./docs-generated


  publish-docs:
    name: Publish preview docs
    runs-on: ubuntu-latest

    needs: [build-docs, release-preview] # only publish docs, if we have actually released code

    steps:
      - uses: actions/checkout@v1

      - name: Download the generated docs
        uses: actions/download-artifact@v1
        with:
          name: ${{ env.GENERATED_DOCS_ARTIFACT }}
          path: ./docs-generated

      - uses: actions-hub/gcloud@master
        env:
          PROJECT_ID: ${{ secrets.GCLOUD_PROJECT_ID }}
          APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          CLI: gsutil
        with:
          args: -m rsync -r -d ./docs-generated gs://${{ env.DOCS_BUCKET }}


  #
  # Run all unit tests on all relevant operating systems
  #
  unit-tests:
    name: Unit tests
    needs: build-code

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
      fail-fast: false

    runs-on: ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_SDK_VERSION }}
      - name: Run unit tests in Release mode
        run: dotnet test '.\src\test-unit\unittests.csproj' -c Release -f netcoreapp2.0

  #
  # Run our functional tests
  #
  functional-tests:
    name: Functional tests
    needs: build-code

    # Note that we would prefer running the functional
    # tests on all supported operating systems, but due
    # to limitations in Github Actions, it is only possible
    # use "services" on Linux
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:3.4
        ports:
          - 27017:27017
      redis-server:
        image: redis:3.2
        ports:
          - 6379:6379
      postgresql:
        image: postgres:10.1-alpine
        ports:
          - 5432:5432
      mssql-server-linux:
        image: microsoft/mssql-server-linux:2017-CU6
        env:
          ACCEPT_EULA: Y
          SA_PASSWORD: "sql-s3rv3r%"
          MSSQL_PID: Developer
        ports:
          - 1433:1433

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_SDK_VERSION }}
      - name: Core tests
        run: dotnet test src/core/test-functional/functionaltests.csproj -c Release
      - name: Google Cloud tests
        run: dotnet test src/google-cloud/test-functional/functionaltests.csproj -c Release
      - name: Mongo tests
        run: dotnet test src/mongo/test-functional/functionaltests.csproj -c Release
      - name: PostgresSql tests
        run: dotnet test src/postgresql/test-functional/functionaltests.csproj -c Release
      - name: SQL Server tests
        run: dotnet test src/sqlserver/test-functional/functionaltests.csproj -c Release
      - name: Redis tests
        run: dotnet test src/redis/test-functional/functionaltest.csproj -c Release



  # Run SonarQube on the solution.
  # This requires us to build the code
  # while the sonar-scanner is running.
  # The same is true for running our tests
  # in order to gather code coverage (which do
  # not actually do yet).
  analyze:
    name: "SonarQube analysis"
    runs-on: ubuntu-latest

    needs: [build-code, unit-tests]

    steps:
      - uses: actions/checkout@v1
      
      # Get the version of the code to report to SonarQube
      - name: Extract info from info_for_actions.json
        shell: bash
        id: extract_info
        run: |
          clean=$(jq -r .version ./info_for_actions.json)
          echo "##[set-output name=version;]$clean"
      
      - name: debug output
        shell: bash
        run: |
          echo Version: ${{ steps.extract_info.outputs.version }}
      
      # Actually run SonarQube
      - uses: Secbyte/dotnet-sonarscanner@v1.2
        with:
          buildCommand: dotnet build -c Release
          testCommand: dotnet test src/test-unit/unittests.csproj -c Release
          projectKey: rapidcore_rapidcore
          projectName: rapidcore
          sonarOrganisation: rapidcore
          # relative paths to source directories. More details and properties are described
          # in https://sonarcloud.io/documentation/project-administration/narrowing-the-focus/ 
          beginArguments: /d:sonar.verbose="true" /d:sonar.sources="./src" /d:sonar.exclusions=./src/test-unit /v:${{ steps.extract_info.outputs.version }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release-preview:
    name: Release preview packages
    runs-on: ubuntu-latest

    needs: [build-code, unit-tests, functional-tests] # only release, if code seems to be ok

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_SDK_VERSION }}
      - name: Figure out the version
        id: version
        shell: pwsh
        run: |
          . cicd_tools/Get-Version.ps1
          $version = Get-Version Preview
          Write-Host "##[set-output name=value;]$version"
      - name: Debug
        shell: bash
        run: |
          echo branch: ${{ steps.version.outputs.value }}
      - name: Restore and build packages
        shell: bash
        run: |
          dotnet restore
          dotnet build -c Release

      - name: Make non-Core packages, use Core from NuGet
        shell: pwsh
        run: |
          ./cicd_tools/Use-NuGetReference.ps1 ${{ steps.version.outputs.value }}
      - name: Pack all packages
        shell: pwsh
        run: |
          . ./cicd_tools/Get-MainProjects.ps1
          $mainProjects = Get-MainProjects "src\"
          $version = "${{ steps.version.outputs.value }}"
          foreach ($csproj in $mainProjects) {
              # Explicitly set the package version to include any version suffixes...
              & dotnet pack $csproj -c Release -o ..\..\..\nuget-artifacts --include-source --no-build --no-restore /p:PackageVersion=$version /p:IncludeSymbols=true /p:SymbolPackageFormat=snupkg
          }
      - name: Push NuGet packages
        shell: bash
        run: |
          # ls -l nuget-artifacts
          cd nuget-artifacts
          dotnet nuget push **/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source ${{ env.NUGET_SOURCE }}
